import uuid
from datetime import datetime, timezone
from typing import Generic, List, Optional, Type, TypeVar
from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession
from app.models.base import BaseModel

ModelType = TypeVar("ModelType", bound=BaseModel)

class BaseRepository(Generic[ModelType]):
    """
    Generic Asynchronous Repository Pattern Implementation for SQLAlchemy 2.0.
    Automatically supports soft-delete filtering.
    """
    def __init__(self, model: Type[ModelType], db: AsyncSession):
        self.model = model
        self.db = db

    async def get_by_id(self, id: uuid.UUID, include_deleted: bool = False) -> Optional[ModelType]:
        """Fetches a single model instance by UUID."""
        query = select(self.model).where(self.model.id == id)
        if not include_deleted:
            query = query.where(self.model.is_deleted == False)
            
        result = await self.db.execute(query)
        return result.scalar_one_or_none()

    async def get_all(
        self, 
        skip: int = 0, 
        limit: int = 100, 
        include_deleted: bool = False
    ) -> List[ModelType]:
        """Fetches multiple records with pagination."""
        query = select(self.model)
        if not include_deleted:
            query = query.where(self.model.is_deleted == False)
            
        query = query.offset(skip).limit(limit)
        result = await self.db.execute(query)
        return list(result.scalars().all())

    async def create(self, obj_in: ModelType) -> ModelType:
        """Persists a new entity instance in the database."""
        self.db.add(obj_in)
        await self.db.flush()  # Populates autogenerated fields (like id, timestamps)
        return obj_in

    async def update(self, db_obj: ModelType, update_data: dict) -> ModelType:
        """Updates an existing database object with a dictionary of changes."""
        for field in update_data:
            if hasattr(db_obj, field):
                setattr(db_obj, field, update_data[field])
                
        # Automatically update updated_at if not handled by database event
        db_obj.updated_at = datetime.now(timezone.utc)
        self.db.add(db_obj)
        await self.db.flush()
        return db_obj

    async def delete(self, id: uuid.UUID, deleter_id: Optional[uuid.UUID] = None) -> bool:
        """
        Executes a soft-delete on the model instance.
        Sets is_deleted = True and deleted_at = now.
        """
        db_obj = await self.get_by_id(id)
        if not db_obj:
            return False
            
        db_obj.is_deleted = True
        db_obj.deleted_at = datetime.now(timezone.utc)
        if deleter_id:
            db_obj.updated_by = deleter_id
            
        self.db.add(db_obj)
        await self.db.flush()
        return True

    async def hard_delete(self, id: uuid.UUID) -> bool:
        """Permanently deletes the record from the database."""
        db_obj = await self.get_by_id(id, include_deleted=True)
        if not db_obj:
            return False
            
        await self.db.delete(db_obj)
        await self.db.flush()
        return True
